# -*- coding: utf-8 -*-
"""ML-DecisionTree

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GLscEIKTxhQbPW0urOePgmgsyf_nZ0hG
"""

#practice from CodeBasics yt channel
# video url = https://www.youtube.com/watch?v=PHxYNGo8NcI&list=PLeo1K3hjS3uvCeTYTeyfe0-rN5r8zn9rw&index=10

import pandas as pd
link = "https://raw.githubusercontent.com/codebasics/py/master/ML/9_decision_tree/Exercise/titanic.csv"
df1 = pd.read_csv(link)
df1.head()

input1 = df1.drop('Name', axis='columns')
input2 = input1.drop('Survived', axis='columns')
input3 = input2.drop('Ticket', axis='columns')
input4 = input3.drop('Cabin', axis='columns')
input5 = input4.drop('Embarked', axis='columns')
input6 = input5.drop('PassengerId', axis='columns')
input7 = input6.drop('SibSp', axis='columns')
input8 = input7.drop('Parch', axis='columns')
target1 = df1['Survived']

input8

target1

from sklearn.preprocessing import LabelEncoder

Pclass = LabelEncoder()
Sex = LabelEncoder()
Age = LabelEncoder()
Fare = LabelEncoder()

input8['Pclass_n'] = Pclass.fit_transform(input8['Pclass'])
input8['Sex_n'] = Sex.fit_transform(input8['Sex'])
input8['Age_n'] = Age.fit_transform(input8['Age'])
input8['Fare_n'] = Fare.fit_transform(input8['Fare'])
input8.head()

input8_n = input8.drop(['Pclass', 'Sex', 'Age','Fare'], axis='columns')
input8_n

from sklearn import tree

model = tree.DecisionTreeClassifier()
model.fit(input8_n,target1)

model.score(input8_n,target1)

model.predict([[0,0,51,207]])